//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SECHProjeEntities : DbContext
    {
        public SECHProjeEntities()
            : base("name=SECHProjeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblDetail> tblDetails { get; set; }
        public DbSet<tblDeveloper> tblDevelopers { get; set; }
        public DbSet<tblTeam> tblTeams { get; set; }
        public DbSet<tblUnit> tblUnits { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblProject> tblProjects { get; set; }
    }
}
