//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblDeveloper
    {
        public tblDeveloper()
        {
            this.tblTeams = new HashSet<tblTeam>();
        }

        [Display(Name = "ID")]
        public int ID { get; set; }

        [Display(Name = "İsim")]
        public string AD { get; set; }

        [Display(Name = "Birim")]
        public int UNIT_ID { get; set; }

        [Display(Name = "Yetki")]
        public Nullable<int> YETKI { get; set; }

        [Display(Name = "Sicil No")]
        public string SICIL_NO { get; set; }
    
        public virtual tblUnit tblUnit { get; set; }
        public virtual ICollection<tblTeam> tblTeams { get; set; }
    }
}
