//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblDetail
    {
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Display(Name = "Proje ID")]
        public int PROJE_ID { get; set; }

        [Display(Name = "Notlar")]
        public string NOTLAR { get; set; }

        [Display(Name = "Yapılan Çalışma")]
        public string YAPILAN_CALISMA { get; set; }

        [Display(Name = "Çalışma Tarihi")]
        public System.DateTime CALISMA_TARIH { get; set; }
    
        public virtual tblProject tblProject { get; set; }
    }
}
