//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tblTeam
    {
        public int ID { get; set; }

        [Display(Name = "Proje ID")]
        public int PROJECT_ID { get; set; }

        [Display(Name = "Kullanıcı ID")]
        public int DEVELOPER_ID { get; set; }
    
        public virtual tblDeveloper tblDeveloper { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
